### ISSUE TITLE
chore: meta tags for social sharing

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_ranch#157]
As a player,
I want to have meta tags,
So that it's easier to share the game with my friends!

- [x] Thumbnail designs - [Open Graph](https://www.figma.com/file/NsjiEkSlrUrpH7jNam0oQ4/Very-Good-Ranch-Studies?node-id=461%3A61877)
- [x] Thumbnail designs - [Social Images](https://www.figma.com/file/NsjiEkSlrUrpH7jNam0oQ4/Very-Good-Ranch-Studies?node-id=461%3A64682)
- [ ] Determine Meta Tags
- [ ] Update the Meta Tags

Example of the image used:
https://firebasestorage.googleapis.com/v0/b/io-pinball.appspot.com/o/images%2Fpinball_share_image.png?alt=media

Meta Tag Template:
https://www.figma.com/community/file/1095923018607050646
